services:
  - type: web
    name: telegram-bot
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        scope: run
        value: YOUR_BOT_TOKEN_HERE
        
